#!/usr/bin/env sh
# Turn on echo
set -x 

echo "STARTED $(date +%Y.%m.%d_%H.%M)"
. "/mnt/user/nas/Files/script/library/library_copy.sh"

################################
## Parameters
################################
BACKUP_NAME="dokuwiki"
source_dir="${DIR_APPDATA}"
tar_source="dokuwiki/dokuwiki/data"
KUMA_TOKEN="Igo1BJdDsW"

tar_copy "$BACKUP_NAME" "$source_dir" "$tar_source" "$KUMA_TOKEN"

echo "COMPLETED $(date +%Y.%m.%d_%H.%M)"
